name: dart_azampay
description: Dart AzamPay is a Dart package that provides a simple and efficient way to integrate AzamPay payment gateway into your Dart/Flutter applications. With Azampay, you can easily make mobile and bank payments, post checkouts, disbursements, and pay bills.
version: 0.0.1
repository: https://github.com/kaykhahima/dart_azampay

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.24.0
